package com.workloom.workloom.dto;

/**
 * Data Transfer Object for Certification section in User Profile.
 */
public class CertificationDto {

    private Long id;
    private String name;
    private String issuingOrganization;
    private String issueDate;
    private String expirationDate;
    private String credentialId;
    private String credentialUrl;

    // No-arg constructor
    public CertificationDto() {
    }

    // All-args constructor (optional)
    public CertificationDto(Long id, String name, String issuingOrganization, String issueDate,
                            String expirationDate, String credentialId, String credentialUrl) {
        this.id = id;
        this.name = name;
        this.issuingOrganization = issuingOrganization;
        this.issueDate = issueDate;
        this.expirationDate = expirationDate;
        this.credentialId = credentialId;
        this.credentialUrl = credentialUrl;
    }

    // Getters and setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getIssuingOrganization() {
        return issuingOrganization;
    }

    public void setIssuingOrganization(String issuingOrganization) {
        this.issuingOrganization = issuingOrganization;
    }

    public String getIssueDate() {
        return issueDate;
    }

    public void setIssueDate(String issueDate) {
        this.issueDate = issueDate;
    }

    public String getExpirationDate() {
        return expirationDate;
    }

    public void setExpirationDate(String expirationDate) {
        this.expirationDate = expirationDate;
    }

    public String getCredentialId() {
        return credentialId;
    }

    public void setCredentialId(String credentialId) {
        this.credentialId = credentialId;
    }

    public String getCredentialUrl() {
        return credentialUrl;
    }

    public void setCredentialUrl(String credentialUrl) {
        this.credentialUrl = credentialUrl;
    }

    @Override
    public String toString() {
        return "CertificationDto{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", issuingOrganization='" + issuingOrganization + '\'' +
                ", issueDate='" + issueDate + '\'' +
                ", expirationDate='" + expirationDate + '\'' +
                ", credentialId='" + credentialId + '\'' +
                ", credentialUrl='" + credentialUrl + '\'' +
                '}';
    }

    // equals() and hashCode() can be autogenerated as needed
}
